// <auto-generated />
using FinanAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinanAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinanAPI.Models.Salario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cargo")
                        .HasColumnType("int");

                    b.Property<double>("GastosLazer")
                        .HasColumnType("float");

                    b.Property<double>("GastosObrigatorios")
                        .HasColumnType("float");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ValorEmergencial")
                        .HasColumnType("float");

                    b.Property<double>("ValorFinal")
                        .HasColumnType("float");

                    b.Property<double>("ValorGuardado")
                        .HasColumnType("float");

                    b.Property<double>("ValorLiquido")
                        .HasColumnType("float");

                    b.Property<double>("valor")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("TB_SALARIOS");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cargo = 5,
                            GastosLazer = 400.0,
                            GastosObrigatorios = 600.0,
                            Nome = "Matheus Estagiário",
                            ValorEmergencial = 100.0,
                            ValorFinal = 500.0,
                            ValorGuardado = 400.0,
                            ValorLiquido = 1500.0,
                            valor = 0.0
                        },
                        new
                        {
                            Id = 2,
                            Cargo = 4,
                            GastosLazer = 500.0,
                            GastosObrigatorios = 600.0,
                            Nome = "Matheus Trainee",
                            ValorEmergencial = 146.5,
                            ValorFinal = 746.5,
                            ValorGuardado = 600.0,
                            ValorLiquido = 1846.5,
                            valor = 0.0
                        },
                        new
                        {
                            Id = 3,
                            Cargo = 3,
                            GastosLazer = 700.0,
                            GastosObrigatorios = 600.0,
                            Nome = "Matheus Júnior",
                            ValorEmergencial = 200.0,
                            ValorFinal = 1200.0,
                            ValorGuardado = 1000.0,
                            ValorLiquido = 2500.0,
                            valor = 0.0
                        },
                        new
                        {
                            Id = 4,
                            Cargo = 2,
                            GastosLazer = 1500.0,
                            GastosObrigatorios = 600.0,
                            Nome = "Matheus Pleno",
                            ValorEmergencial = 400.0,
                            ValorFinal = 2900.0,
                            ValorGuardado = 2500.0,
                            ValorLiquido = 5000.0,
                            valor = 0.0
                        },
                        new
                        {
                            Id = 5,
                            Cargo = 1,
                            GastosLazer = 3000.0,
                            GastosObrigatorios = 600.0,
                            Nome = "Matheus Sênior",
                            ValorEmergencial = 900.0,
                            ValorFinal = 4400.0,
                            ValorGuardado = 3500.0,
                            ValorLiquido = 8000.0,
                            valor = 0.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
